# Generated by Django 5.2.9 on 2025-12-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_authtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
