# Generated by Django 5.2.9 on 2025-12-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tempuser_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
